{"name": "test_login_for_a_invalid_credential", "status": "passed", "start": 1713419735820, "stop": 1713419736241, "uuid": "c9857b0d-874b-402f-b4e2-c638e4f5a8c3", "historyId": "be552f75a8f0cdeb13174fa17097e01a", "testCaseId": "be552f75a8f0cdeb13174fa17097e01a", "fullName": "test.test_LoginErrorMessage.TestLoginErrorMessage#test_login_for_a_invalid_credential", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown')"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_LoginErrorMessage"}, {"name": "subSuite", "value": "TestLoginErrorMessage"}, {"name": "host", "value": "HMECL008608"}, {"name": "thread", "value": "26484-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_LoginErrorMessage"}]}